import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Grid, GridItem } from '@chakra-ui/react'
import { useState, useEffect } from 'react'

export default function Home() {

  const [coursesList, setCoursesList] = useState([]);
  // async function getCourses() {
  //   const response = await fetch("localhost:3000/courses");
  //   const data = await response.json();
  //   console.log(data);
  //   return data
  //   };

    useEffect(() => {
      async function fetchCourses() {
        const res = await fetch("/coulocalhost:3000/coursesrses");
        const json = await res.json();
        setCoursesList(json.Payload);
      }
      fetchCourses();
    }, );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
  templateAreas={`"header header"
                  "nav main"
                  "nav footer"`}
  gridTemplateRows={'50px 1fr 30px'}
  gridTemplateColumns={'150px 1fr'}
  h='200px'
  gap='1'
  color='blackAlpha.700'
  fontWeight='bold'
>
  <GridItem pl='2' bg='orange.300' area={'header'}>
    OPEN STUDY COLLEGE COURSES
  </GridItem>
  <GridItem pl='2' bg='pink.300' area={'nav'}>
    Nav
    {console.log(coursesList)}
  </GridItem>
  <GridItem pl='2' bg='green.300' area={'main'}>
    Main
  </GridItem>
  <GridItem pl='2' bg='blue.300' area={'footer'}>
    Footer
  </GridItem>
</Grid>
    </div>
  )
}